name: OWASP DevSecOps CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  sast:
    name: Static Code Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm \
            -v $(pwd):/src \
            owasp/dependency-check \
            --scan /src \
            --format HTML \
            --out reports/

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-scan-results
          path: ./scan-results/

  dast:
    name: Dynamic App Security Testing (DAST)
    runs-on: ubuntu-latest
    needs: [sast, dependency-check]
    steps:
      - name: Start Application
        run: |
          docker build -t devsecops-sample .
          docker run -d -p 3000:3000 devsecops-sample

      - name: Run OWASP ZAP (DAST)
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
            -t http://localhost:3000 \
            -r zap_report.html

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html

  secrets:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run GitLeaks
        run: |
          docker run --rm -v $(pwd):/repo zricethezav/gitleaks detect --source=/repo

  container-security:
    name: Container Security (Trivy)
    runs-on: ubuntu-latest
    needs: [dependency-check, dast, secrets]
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy-linux-amd64
          chmod +x trivy-linux-amd64
          sudo mv trivy-linux-amd64 /usr/local/bin/trivy

      - name: Run Trivy Scan
        run: trivy image devsecops-sample > trivy_report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy_report.txt

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [container-security]
    steps:
      - name: Deploy Application
        run: echo "Deploying Secure App!"
